spring:
  application:
    name: notes-community
  kafka:
    # 对应 Docker 容器 exposed ports (KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092)
    bootstrap-servers: 127.0.0.1:9092
    producer:
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: notes-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/kamanote_tech?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: root
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#    sentinel:
#      transport:
#        dashboard: 127.0.0.1:8858
#
#dubbo:
#  application:
#    name: notes-community
#    qos-enable: false
#    logger: slf4j
#  protocol:
#    name: tri
#    port: -1
#  registry:
#    address: nacos://127.0.0.1:8848?username=nacos&password=nacos
#    register-mode: instance
#    parameters:
#      namespace: 3aeb0b4e-650a-4024-8c27-cb56242d0bd1
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#seata:
#  client:
#    undo:
#      log-serialization: jackson