server:
  port: 8002

jwt:
  secret: abc123
  expiration: 2592000

spring:
  application:
    name: notes-auth
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8858
      eager: true

dubbo:
  application:
    name: notes-auth
    qos-enable: false
    logger: slf4j
  protocol:
    name: tri
    port: -1
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848?username=nacos&password=nacos
    register-mode: instance
    parameters:
      namespace: 3aeb0b4e-650a-4024-8c27-cb56242d0bd1
