#upload:
#  path: ${user.dir}/tmp/uploads # 指定上传文件的存储路径
#  url-prefix: http://localhost:8008/images  # 访问上传文件的URL前缀
#
#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#    sentinel:
#      transport:
#        dashboard: 127.0.0.1:8858
#  servlet:
#    multipart:
#      max-file-size: 50MB
#      max-request-size: 50MB
#
#dubbo:
#  application:
#    name: notes-file
#    qos-enable: false
#    logger: slf4j
#  protocol:
#    name: tri
#    port: -1
#  registry:
#    address: nacos://127.0.0.1:8848?username=nacos&password=nacos
#    register-mode: instance
#    parameters:
#      namespace: 3aeb0b4e-650a-4024-8c27-cb56242d0bd1