#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/kamanote_tech?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: root
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#    sentinel:
#      transport:
#        dashboard: 127.0.0.1:8858
#
#dubbo:
#  application:
#    name: notes-note
#    qos-enable: false
#    logger: slf4j
#  protocol:
#    name: tri
#    port: -1
#  registry:
#    address: nacos://127.0.0.1:8848?username=nacos&password=nacos
#    register-mode: instance
#    parameters:
#      namespace: 3aeb0b4e-650a-4024-8c27-cb56242d0bd1
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#seata:
#  client:
#    undo:
#      log-serialization: jackson

dubbo:
  application:
    serialize-check-status: WARN
    serialize-allow-list: com.pomdetom.notes.common.model.**